version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongo
    networks:
      - mern-network

  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - JWT_EXPIRE=30
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mernapp
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - SERVER_ID=server1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - mern-network

  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - JWT_EXPIRE=30
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mernapp
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - SERVER_ID=server2
    networks:
      - mern-network

  load-balancer:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
      - client
    networks:
      - mern-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_URL=http://load-balancer/api/v1  # Используйте публичный URL балансировщика
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local