version: '3'

services:
  # MongoDB сервис
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  # Добавляем MongoDB Express (веб-интерфейс для MongoDB)
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    depends_on:
      - mongo
    networks:
      - mern-network

  # Первый сервер Express (server1)
  server1:
    build: 
      context: ./server
      dockerfile: Dockerfile
    # Убираем внешнее отображение порта, так как теперь доступ будет через балансировщик
    expose:
      - "5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mernapp
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - SERVER_ID=server1
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-network

  # Второй сервер Express (server2) - копия первого
  server2:
    build: 
      context: ./server
      dockerfile: Dockerfile
    expose:
      - "5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/mernapp
      - JWT_SECRET=your_jwt_secret_key
      - NODE_ENV=development
      - SERVER_ID=server2
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mern-network

  # Балансировщик нагрузки (Nginx)
  load-balancer:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - server1
      - server2
    networks:
      - mern-network

  # Клиентская часть (React + Vite)
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:5000
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local

